services:
  - type: web
    name: app
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app --chdir backend

  - type: web
    name: news
    env: python
    buildCommand: ""
    startCommand: uvicorn news:app --chdir backend --host 0.0.0.0 --port 8000
